
# ===============================
# Application Name
# ===============================

spring.application.name=java_web_25

# ===============================
# Log File Configuration
# ===============================
logging.file.name=logs/${spring.application.java_web_25}.log
logging.file.path=logs

# ===============================
# Log Pattern
# ===============================
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg %X{traceId}%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg %X{traceId}%n

# ===============================
# Log Levels
# ===============================
logging.level.root=INFO

# Application package logging
logging.level.com.yourcompany=DEBUG

# Reduce framework noise
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.apache.catalina=WARN

# ===============================
# Log Rolling Policy (Spring Boot 2.5+)
# ===============================
logging.logback.rollingpolicy.file-name-pattern=logs/${spring.application.name}-%d{yyyy-MM-dd}.log
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB


# ===============================
# DATABASE CONFIGURATION POSTGRES
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Amar@macm1!#
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# ===============================
# CONNECTION POOL (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
